#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-jpype1
Version  : 1.4.1
Release  : 18
URL      : https://files.pythonhosted.org/packages/1b/eb/3e9696c3feda2d70a866a3f62880b9eb77187d7b188436d3f480c2f4842c/JPype1-1.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/1b/eb/3e9696c3feda2d70a866a3f62880b9eb77187d7b188436d3f480c2f4842c/JPype1-1.4.1.tar.gz
Summary  : A Python to Java bridge.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-jpype1-license = %{version}-%{release}
Requires: pypi-jpype1-python = %{version}-%{release}
Requires: pypi-jpype1-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(packaging)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
.. image:: doc/logo.png
:scale: 50 %
:alt: JPype logo
:align: center
JPype
=====

|implementation|  |pyversions|  |javaversions|  |jvm|  |platform|  |license|

%package license
Summary: license components for the pypi-jpype1 package.
Group: Default

%description license
license components for the pypi-jpype1 package.


%package python
Summary: python components for the pypi-jpype1 package.
Group: Default
Requires: pypi-jpype1-python3 = %{version}-%{release}

%description python
python components for the pypi-jpype1 package.


%package python3
Summary: python3 components for the pypi-jpype1 package.
Group: Default
Requires: python3-core
Provides: pypi(jpype1)
Requires: pypi(packaging)

%description python3
python3 components for the pypi-jpype1 package.


%prep
%setup -q -n JPype1-1.4.1
cd %{_builddir}/JPype1-1.4.1
pushd ..
cp -a JPype1-1.4.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683039500
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jpype1
cp %{_builddir}/JPype1-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jpype1/adeb06dcb98997b978442c639092e33885dc4afc || :
cp %{_builddir}/JPype1-%{version}/NOTICE %{buildroot}/usr/share/package-licenses/pypi-jpype1/523827acd23caa6282e6aa25436ba1f1cf49fa92 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jpype1/523827acd23caa6282e6aa25436ba1f1cf49fa92
/usr/share/package-licenses/pypi-jpype1/adeb06dcb98997b978442c639092e33885dc4afc

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
